services:
    # Pi-Hole DNS
    pihole:
        container_name: pihole
        hostname: pihole
        image: pihole/pihole:latest # remember to change this if you're using rpi
        networks:
            dns_net:
                ipv4_address: 172.23.0.7
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "85:80/tcp"
            #- "443:443/tcp"
        environment:
            - TZ=${TZ}
            - WEBPASSWORD=${PIHOLE_PASSWORD}
            - FTLCONF_LOCAL_IPV4=${HOST_LOCAL_IPV4}
            - PIHOLE_DNS=${PIHOLE_DNSFORWARDER}
        volumes:
            - '$DOCKERDIR/volumes/pihole/etc-pihole/:/etc/pihole/'
            - '$DOCKERDIR/volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        restart: unless-stopped
        profiles: ["core", "all"]