########################### OCR'S ENVIRONMENT

# Here are my 5 Docker compose:
# - Home Server (Home-Docker) - Proxmox LXC with Ubuntu Server 22.04
# - DNS / AdBlock Server (dns) - Raspberry Pi 4B with Raspberry Pi OS


########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  reverse_proxy:
    name: reverse_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16     
  dns_net:
    name: dns_net
    driver: bridge
    ipam:
        config:
        - subnet: 172.23.0.0/16  


########################### SECRETS

########################### SERVICES
include:

  # Specific - $HOME/mydocker/services/compose/$HOSTNAME/includes/<service_name>.yml
  # shared - $HOME/mydocker/services/compose/shared/includes/<service_name>.yml

  # CORE
  - $HOME/mydocker/services/compose/shared/includes/cloufflare-ddns.yml
  - $HOME/mydocker/services/compose/shared/includes/unbound.yml
  - $HOME/mydocker/services/compose/shared/includes/pihole.yml
  - $HOME/mydocker/services/compose/shared/includes/portainer-ce.yml

  # SERVICES
  - $HOME/mydocker/services/compose/shared/includes/whatchtower.yml
  - $HOME/mydocker/services/compose/shared/includes/cloudflare-companion.yml

  # APPS
  - $HOME/mydocker/services/compose/shared/includes/bitwarden.yml
  - $HOME/mydocker/services/compose/shared/includes/wireguard.yml