services:
    # Cloudflare Traefik Companion
    cloudflare-companion:
        image: tiredofit/traefik-cloudflare-companion:latest
        container_name: cloudflare-companion
        environment:
            - TIMEZONE=${TZ}
            - TRAEFIK_VERSION=2
            - CF_TOKEN=${CLOUDFLARE_TOKEN}
            - TARGET_DOMAIN=${CLOUDFLARE_DOMAIN1}
            - DOMAIN1=${CLOUDFLARE_DOMAIN1}
            - DOMAIN1_ZONE_ID=${CLOUDFLARE_DOMAIN1_ZONEID}
            - DOMAIN1_PROXIED=TRUE
        network_mode: 'host'    
        volumes:
            - $DOCKERDIR/volumes/cloudflare-companion/logs:/logs
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        profiles: ["services", "all"]
