services:
    # Cloudflare DDNS
    cloudflare-ddns:
        image: timothyjmiller/cloudflare-ddns:latest
        container_name: cloudflare-ddns
        security_opt:
            - no-new-privileges:true
        network_mode: 'host'
        volumes:
            - $DOCKERDIR/volumes/cloudflare-ddns/config.json:/config.json
        restart: unless-stopped
        profiles: ["core", "all"]