services:    
    # ghost
    ghost:
        image: ghost:5-alpine
        container_name: ghost
        restart: unless-stopped
        profiles: ["apps", "all"]
        # ports:
        #    - 8080:2368
        environment:
            # see https://ghost.org/docs/config/#configuration-options
            - database__client=$GHOST_DB_CLIENT
            - database__connection__host=$GHOST_DB_HOSTNAME
            - database__connection__user=$GHOST_DB_ROOT_USER
            - database__connection__password=$GHOST_DB_ROOT_PASSWORD
            - database__connection__database=$GHOST_DB_DBNAME
            - url=https//ghost.${PUBLICDOMAIN1}
        volumes:
            - $DOCKERDIR/volumes/ghost:/var/lib/ghost/content    

        networks:
            - reverse_proxy
            - backend  
        labels:
            traefik.enable: true
            traefik.http.routers.ghost.rule: Host(`ghost.${PUBLICDOMAIN1}`)
            traefik.http.services.ghost.loadbalancer.server.port: 2368
            traefik.http.routers.ghost.middlewares: https_redirect@file
            traefik.http.routers.ghost.tls.certresolver: myresolver
            traefik.http.routers.ghost.entrypoints: web,websecure
            traefik.constraint: reverse_proxy # cloudlare-companion constraints

    ghost-db:
        image: mysql:8.0
        restart: always
        profiles: ["apps", "all"]
        environment:
            - MYSQL_ROOT_PASSWORD=$GHOST_DB_ROOT_PASSWORD
        networks:
            - backend      
        volumes:
            - $DOCKERDIR/volumes/ghost-db:/var/lib/mysql