services:
    # Unbound DNS (used as DNS fowarder)
    unbound:
        container_name: unbound
        image: mvance/unbound:latest # remember to change this if you're using rpi
        networks:
            dns_net:
                ipv4_address: 172.23.0.8
        volumes:
            - $DOCKERDIR/volumes/unbound:/opt/unbound/etc/unbound
        ports:
            - "5053:53/tcp"
            - "5053:53/udp"
        healthcheck:
            test: ["NONE"]
        restart: unless-stopped
        profiles: ["core", "all"]